language: node_js
node_js:
  - "8"
  - "10"
  - "12"
services: mongodb  
cache:  
  directories:
    - "node_modules"
sudo: false
install:
  - npm install
script:
  - npm run lint
  - npm test
deploy:
  provider: heroku
  api_key:
    secure: iT2RTzO-hE_yOBtxIzfVmA
  app: Docker-CICD