language: node_js
node_js:
  - "8"
  - "10"
  - "12"
services: mongodb  
cache:  
  directories:
    - "node_modules"
sudo: false
install:
  - npm install
script:
  - npm run lint
  - npm test
deploy:
  provider: heroku
  api_key:
    secure: 1f1ab659-150b-44e2-877d-d9644f90073d
  app: Docker-CICD